project_id = "zipqraqiztulxyuzhtjo"

[functions.api-productos]
verify_jwt = false

[functions.afip-facturacion]
verify_jwt = false

[functions.solicitar-descuento]
verify_jwt = false

[functions.validar-token-descuento]
verify_jwt = false

[functions.aprobar-descuento]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.manage-push-subscription]
verify_jwt = false

[functions.generar-token-admin]
verify_jwt = false

[functions.chat-asistente]
verify_jwt = false

